//! OCCT Binding Generator Library
//!
//! This library parses OCCT C++ headers and generates CXX bridge code,
//! organized into per-module Rust files with type aliasing for cross-module references.

pub mod codegen;
pub mod model;
pub mod module_graph;
pub mod parser;
pub mod type_mapping;

use anyhow::Result;
use std::path::Path;

/// Result of code generation for a single module
pub struct GeneratedModule {
    /// Module name (e.g., "gp", "topo_ds")
    pub rust_name: String,
    /// Generated Rust code
    pub rust_code: String,
    /// Generated C++ header wrapper
    pub cpp_code: String,
}

/// Configuration for binding generation
pub struct GeneratorConfig<'a> {
    /// OCCT headers to process
    pub headers: &'a [&'a Path],
    /// Include directories for libclang
    pub include_dirs: &'a [&'a Path],
    /// Enable verbose output
    pub verbose: bool,
}

/// Generate bindings from OCCT headers
///
/// Returns a list of generated modules (Rust + C++ code) and the common header.
pub fn generate_bindings(config: &GeneratorConfig) -> Result<(Vec<GeneratedModule>, String)> {
    let headers: Vec<_> = config.headers.iter().map(|p| p.to_path_buf()).collect();
    let include_dirs: Vec<_> = config.include_dirs.iter().map(|p| p.to_path_buf()).collect();

    // Parse headers
    let parsed = parser::parse_headers(&headers, &include_dirs, config.verbose)?;

    // Build module dependency graph
    let graph = module_graph::ModuleGraph::from_headers(&parsed);

    // Generate common header
    let common_hxx = codegen::cpp::generate_common_header();

    // Collect all classes and enums
    let all_classes: Vec<_> = parsed.iter().flat_map(|h| &h.classes).collect();
    let all_enums: Vec<_> = parsed.iter().flat_map(|h| &h.enums).collect();

    let mut modules = Vec::new();

    // Generate modules in dependency order
    let ordered = graph.modules_in_order();
    for module in ordered {
        // Get classes for this module
        let module_classes: Vec<_> = all_classes
            .iter()
            .filter(|c| c.module == module.name)
            .copied()
            .collect();

        // Get enums for this module
        let module_enums: Vec<_> = all_enums
            .iter()
            .filter(|e| e.module == module.name)
            .copied()
            .collect();

        if module_classes.is_empty() && module_enums.is_empty() {
            continue;
        }

        // Get cross-module types
        let cross_types = graph.get_cross_module_types(&module.name);

        // Generate Rust code
        let rust_code =
            codegen::rust::generate_module(module, &module_classes, &module_enums, &cross_types);

        // Generate C++ header
        let cpp_code = codegen::cpp::generate_module_header(module, &module_classes, &cross_types);

        modules.push(GeneratedModule {
            rust_name: module.rust_name.clone(),
            rust_code: rust_code.to_string(),
            cpp_code,
        });
    }

    Ok((modules, common_hxx))
}

/// Generate the lib.rs content that includes all modules
pub fn generate_lib_rs(modules: &[GeneratedModule]) -> String {
    let mut content = String::new();
    content.push_str("// Auto-generated by opencascade-binding-generator\n");
    content.push_str("// Do not edit manually\n\n");

    for module in modules {
        content.push_str(&format!("pub mod {};\n", module.rust_name));
    }

    content
}
