//! C++ wrapper code generation
//!
//! Generates C++ wrapper functions for patterns that CXX can't handle directly:
//! - Constructors (using std::make_unique)
//! - Return-by-value methods
//! - Static methods
//! - Overloaded methods
//!
//! Note: common.hxx is now hand-maintained in opencascade-sys/src/common.hxx,
//! not generated by this module.

use crate::model::{ParsedClass, Type};
use crate::resolver::{self, SymbolTable};
use std::collections::HashSet;
use std::fmt::Write;

fn collect_handle_types(classes: &[&ParsedClass]) -> Vec<(String, String)> {
    let mut handles = HashSet::new();

    for class in classes {
        // Add Handle type for classes that are transient (can be wrapped in Handle)
        if class.is_handle_type && !class.has_protected_destructor {
            handles.insert(class.name.clone());
        }

        for method in &class.methods {
            collect_type_handles(&method.return_type, &mut handles);
            for param in &method.params {
                collect_type_handles(&Some(param.ty.clone()), &mut handles);
            }
        }

        for method in &class.static_methods {
            collect_type_handles(&method.return_type, &mut handles);
            for param in &method.params {
                collect_type_handles(&Some(param.ty.clone()), &mut handles);
            }
        }

        for ctor in &class.constructors {
            for param in &ctor.params {
                collect_type_handles(&Some(param.ty.clone()), &mut handles);
            }
        }
    }

    let mut result: Vec<_> = handles
        .into_iter()
        .filter(|inner_class| {
            // Skip namespace-scoped types (e.g., IMeshData::ListOfPnt2d) and pointer types
            !inner_class.contains("::") && !inner_class.contains('*') && !inner_class.contains('&')
        })
        .map(|inner_class| {
            // Use full class name to match Rust side (e.g., HandleGeom2dCurve not HandleCurve)
            let handle_name = format!("Handle{}", inner_class.replace("_", ""));
            (inner_class, handle_name)
        })
        .collect();
    result.sort();
    result
}


/// Collect Handle type inner classes from a type
fn collect_type_handles(ty: &Option<Type>, handles: &mut HashSet<String>) {
    if let Some(ty) = ty {
        match ty {
            Type::Handle(name) => {
                handles.insert(name.clone());
            }
            Type::ConstRef(inner) | Type::MutRef(inner) | Type::ConstPtr(inner) | Type::MutPtr(inner) => {
                collect_type_handles(&Some(inner.as_ref().clone()), handles);
            }
            _ => {}
        }
    }
}

/// Collect headers needed for a type
fn collect_type_headers(ty: &Option<Type>, headers: &mut HashSet<String>, known_headers: &HashSet<String>) {
    if let Some(ty) = ty {
        // Skip unbindable types (arrays, streams, void pointers, raw pointers, etc.)
        if ty.is_unbindable() {
            return;
        }

        match ty {
            Type::Class(name) => {
                // Skip primitive types that don't have headers
                // Also skip Standard_Address which is defined in Standard_TypeDef.hxx, not its own file
                if matches!(name.as_str(), 
                    "bool" | "char" | "int" | "unsigned" | "float" | "double" | 
                    "void" | "size_t" | "Standard_Address"
                ) {
                    return;
                }
                // Skip nested types (e.g., Message_Messenger::StreamBuffer resolved to just StreamBuffer)
                // OCCT classes follow Module_ClassName pattern, so classes without underscore
                // (except Standard types) are likely nested types that don't have their own header
                if !name.contains('_') && !name.starts_with("Standard") {
                    return;
                }
                // Only include headers that actually exist in the OCCT include directory
                let header = format!("{}.hxx", name);
                if known_headers.is_empty() || known_headers.contains(&header) {
                    headers.insert(header);
                }
            }
            Type::Handle(name) => {
                let header = format!("{}.hxx", name);
                if known_headers.is_empty() || known_headers.contains(&header) {
                    headers.insert(header);
                }
                headers.insert("Standard_Handle.hxx".to_string());
            }
            Type::ConstRef(inner) | Type::MutRef(inner) | Type::ConstPtr(inner) | Type::MutPtr(inner) => {
                collect_type_headers(&Some(inner.as_ref().clone()), headers, known_headers);
            }
            _ => {}
        }
    }
}

fn type_to_cpp_param(ty: &Type) -> String {
    match ty {
        // const char* parameters should accept rust::Str from CXX
        Type::ConstPtr(inner) if matches!(inner.as_ref(), Type::Class(name) if name == "char") => {
            "rust::Str".to_string()
        }
        _ => type_to_cpp(ty),
    }
}

/// Convert a resolved parameter to the argument form needed when calling OCCT functions
fn param_to_cpp_arg_resolved(param: &resolver::ResolvedParam) -> String {
    match &param.ty.original {
        Type::ConstPtr(inner) if matches!(inner.as_ref(), Type::Class(name) if name == "char") => {
            format!("std::string({}).c_str()", param.name)
        }
        _ => param.name.clone(),
    }
}

/// Convert our Type to C++ type string
fn type_to_cpp(ty: &Type) -> String {
    match ty {
        Type::Void => "void".to_string(),
        Type::Bool => "Standard_Boolean".to_string(),
        Type::I32 => "Standard_Integer".to_string(),
        Type::U32 => "unsigned int".to_string(),
        Type::I64 => "long".to_string(),
        Type::U64 => "unsigned long long".to_string(),
        Type::Usize => "size_t".to_string(),
        Type::F32 => "float".to_string(),
        Type::F64 => "Standard_Real".to_string(),
        Type::ConstRef(inner) => format!("const {}&", type_to_cpp(inner)),
        Type::MutRef(inner) => format!("{}&", type_to_cpp(inner)),
        Type::RValueRef(inner) => format!("{}&&", type_to_cpp(inner)),
        Type::ConstPtr(inner) => format!("const {}*", type_to_cpp(inner)),
        Type::MutPtr(inner) => format!("{}*", type_to_cpp(inner)),
        Type::Handle(name) => format!("opencascade::handle<{}>", name),
        Type::Class(name) => name.clone(),
    }
}

pub fn generate_unified_wrappers(
    all_classes: &[&ParsedClass],
    collections: &[super::collections::CollectionInfo],
    known_headers: &HashSet<String>,
    symbol_table: &SymbolTable,
    all_bindings: &[super::bindings::ClassBindings],
) -> String {
    let mut output = String::new();

    // Header guard and includes
    writeln!(output, "// Generated by opencascade-binding-generator").unwrap();
    writeln!(output, "// Unified C++ wrappers for all OCCT modules").unwrap();
    writeln!(output).unwrap();
    writeln!(output, "#pragma once").unwrap();
    writeln!(output, "#include \"common.hxx\"").unwrap();
    writeln!(output).unwrap();

    // Collect ALL headers needed
    let headers = collect_all_required_headers(all_classes, known_headers);
    
    for header in &headers {
        writeln!(output, "#include <{}>", header).unwrap();
    }
    writeln!(output).unwrap();

    // Generate Handle typedefs for ALL classes
    let handle_types = collect_handle_types(all_classes);
    if !handle_types.is_empty() {
        writeln!(output, "// Handle type aliases").unwrap();
        for (inner_class, handle_name) in &handle_types {
            writeln!(
                output,
                "typedef opencascade::handle<{}> {};",
                inner_class, handle_name
            )
            .unwrap();
        }
        writeln!(output).unwrap();
    }

    // Generate wrapper functions for ALL classes from pre-computed ClassBindings
    for bindings in all_bindings {
        if bindings.has_protected_destructor {
            continue;
        }
        output.push_str(&super::bindings::emit_cpp_class(bindings));
    }

    // Generate wrappers for ALL namespace-level free functions
    generate_unified_function_wrappers(&mut output, symbol_table, known_headers);

    // Generate collection wrappers
    if !collections.is_empty() {
        output.push_str(&super::collections::generate_unified_cpp_collections(collections));
    }

    output
}

/// Collect ALL OCCT headers needed for all classes
fn collect_all_required_headers(
    classes: &[&ParsedClass],
    known_headers: &HashSet<String>,
) -> Vec<String> {
    let mut headers = HashSet::new();

    for class in classes {
        // Add header for the class itself - use the actual source header
        // (class name doesn't always match header name, e.g. Extrema_GlobOptFuncCCC0 is in Extrema_GlobOptFuncCC.hxx)
        let source_header = &class.source_header;
        if known_headers.is_empty() || known_headers.contains(source_header) {
            headers.insert(source_header.clone());
        } else {
            // Fallback: try class_name.hxx 
            let class_header = format!("{}.hxx", class.name);
            if known_headers.contains(&class_header) {
                headers.insert(class_header);
            }
        }

        // Add headers for types used in methods
        for method in &class.methods {
            collect_type_headers(&method.return_type, &mut headers, known_headers);
            for param in &method.params {
                collect_type_headers(&Some(param.ty.clone()), &mut headers, known_headers);
            }
        }

        for method in &class.static_methods {
            collect_type_headers(&method.return_type, &mut headers, known_headers);
            for param in &method.params {
                collect_type_headers(&Some(param.ty.clone()), &mut headers, known_headers);
            }
        }

        for ctor in &class.constructors {
            for param in &ctor.params {
                collect_type_headers(&Some(param.ty.clone()), &mut headers, known_headers);
            }
        }
    }

    let mut result: Vec<_> = headers.into_iter().collect();
    result.sort();
    result
}

/// Generate wrappers for all namespace-level free functions
fn generate_unified_function_wrappers(
    output: &mut String,
    symbol_table: &SymbolTable,
    known_headers: &HashSet<String>,
) {
    let all_functions = symbol_table.all_included_functions();
    if all_functions.is_empty() {
        return;
    }

    // Group functions by namespace
    let mut by_namespace: std::collections::HashMap<&str, Vec<&resolver::ResolvedFunction>> =
        std::collections::HashMap::new();
    for func in &all_functions {
        by_namespace
            .entry(&func.namespace)
            .or_default()
            .push(func);
    }

    let mut namespaces: Vec<&&str> = by_namespace.keys().collect();
    namespaces.sort();

    for namespace in namespaces {
        let namespace_functions = &by_namespace[namespace];

        writeln!(output, "// ========================").unwrap();
        writeln!(output, "// {} namespace functions", namespace).unwrap();
        writeln!(output, "// ========================").unwrap();

        // Extra headers for this namespace
        let mut extra_headers: HashSet<String> = HashSet::new();
        for func in namespace_functions {
            extra_headers.insert(format!("{}.hxx", namespace));
            for param in &func.params {
                collect_type_headers(&Some(param.ty.original.clone()), &mut extra_headers, known_headers);
            }
            if let Some(ref ret_ty) = func.return_type {
                collect_type_headers(&Some(ret_ty.original.clone()), &mut extra_headers, known_headers);
            }
        }

        let mut sorted_headers: Vec<_> = extra_headers.into_iter().collect();
        sorted_headers.sort();
        for header in &sorted_headers {
            writeln!(output, "#include <{}>", header).unwrap();
        }

        for func in namespace_functions {
            let wrapper_name = &func.cpp_wrapper_name;

            // Check if return type is an enum
            let return_is_enum = func.return_type.as_ref()
                .map(|ty| ty.enum_cpp_name.is_some())
                .unwrap_or(false);

            let return_type_cpp = if return_is_enum {
                "int32_t".to_string()
            } else {
                match &func.return_type {
                    Some(ty) => type_to_cpp(&ty.original),
                    None => "void".to_string(),
                }
            };

            let params_cpp: Vec<String> = func
                .params
                .iter()
                .map(|p| {
                    if p.ty.enum_cpp_name.is_some() {
                        format!("int32_t {}", p.name)
                    } else {
                        format!("{} {}", type_to_cpp_param(&p.ty.original), p.name)
                    }
                })
                .collect();
            let params_str = params_cpp.join(", ");

            let args: Vec<String> = func.params.iter().map(|p| {
                if let Some(ref enum_name) = p.ty.enum_cpp_name {
                    format!("static_cast<{}>({})", enum_name, p.name)
                } else {
                    param_to_cpp_arg_resolved(p)
                }
            }).collect();
            let args_str = args.join(", ");

            let call = format!("{}::{}({})", namespace, func.short_name, args_str);

            // Check if return type is a by-value class or Handle type (needs unique_ptr wrapping)
            let returns_by_value_opaque = match &func.return_type {
                Some(rt) => match &rt.original {
                    Type::Class(name) => !symbol_table.all_enum_names.contains(name),
                    Type::Handle(_) => true,
                    _ => false,
                },
                None => false,
            };

            if return_is_enum {
                writeln!(
                    output,
                    "inline {} {}({}) {{ return static_cast<int32_t>({}); }}",
                    return_type_cpp, wrapper_name, params_str, call
                )
                .unwrap();
            } else if returns_by_value_opaque {
                writeln!(
                    output,
                    "inline std::unique_ptr<{0}> {1}({2}) {{ return std::make_unique<{0}>({3}); }}",
                    return_type_cpp, wrapper_name, params_str, call
                )
                .unwrap();
            } else {
                writeln!(
                    output,
                    "inline {} {}({}) {{ return {}; }}",
                    return_type_cpp, wrapper_name, params_str, call
                )
                .unwrap();
            }
        }
        writeln!(output).unwrap();
    }
}

