//! C++ wrapper code generation
//!
//! Generates C++ wrapper functions for patterns that CXX can't handle directly:
//! - Constructors (using std::make_unique)
//! - Return-by-value methods
//! - Static methods
//! - Overloaded methods
//!
//! Note: common.hxx is now hand-maintained in opencascade-sys/src/common.hxx,
//! not generated by this module.

use crate::model::{Param, ParsedClass, ParsedFunction, Type};
use crate::module_graph::Module;
use crate::resolver::{self, SymbolTable};
use std::collections::HashSet;
use std::fmt::Write;

/// Generate the C++ header for a module
pub fn generate_module_header(
    module: &Module,
    classes: &[&ParsedClass],
    functions: &[&ParsedFunction],
    collections: &[super::collections::CollectionInfo],
    known_headers: &HashSet<String>,
    symbol_table: &SymbolTable,
) -> String {
    let mut output = String::new();

    // Header guard and includes
    writeln!(output, "// Generated by opencascade-binding-generator").unwrap();
    writeln!(output, "// C++ wrappers for {} module", module.name).unwrap();
    writeln!(output).unwrap();
    writeln!(output, "#pragma once").unwrap();
    writeln!(output, "#include \"common.hxx\"").unwrap();
    writeln!(output).unwrap();

    // Collect all OCCT headers needed
    let mut headers = collect_required_headers(classes, known_headers);
    
    // Add headers for collections
    let collection_headers = super::collections::get_collection_headers(collections);
    headers.extend(collection_headers);
    headers.sort();
    headers.dedup();
    
    for header in &headers {
        writeln!(output, "#include <{}>", header).unwrap();
    }
    writeln!(output).unwrap();

    // Generate Handle typedefs
    let handle_types = collect_handle_types(classes);
    if !handle_types.is_empty() {
        writeln!(output, "// Handle type aliases").unwrap();
        for (inner_class, handle_name) in &handle_types {
            writeln!(
                output,
                "typedef opencascade::handle<{}> {};",
                inner_class, handle_name
            )
            .unwrap();
        }
        writeln!(output).unwrap();
    }

    // Generate wrapper functions for each class
    for class in classes {
        generate_class_wrappers(class, &mut output, symbol_table);
    }

    // Generate wrappers for namespace-level free functions
    generate_function_wrappers(&module.name, functions, &mut output, symbol_table, known_headers);

    // Generate collection wrappers
    if !collections.is_empty() {
        output.push_str(&super::collections::generate_module_cpp_collections(collections));
    }

    output
}

/// Collect all OCCT headers needed for a set of classes
fn collect_required_headers(classes: &[&ParsedClass], known_headers: &HashSet<String>) -> Vec<String> {
    let mut headers = HashSet::new();

    for class in classes {
        // Add header for the class itself (only if it exists as a separate header)
        let class_header = format!("{}.hxx", class.name);
        if known_headers.is_empty() || known_headers.contains(&class_header) {
            headers.insert(class_header);
        }

        // Add headers for types used in methods
        for method in &class.methods {
            collect_type_headers(&method.return_type, &mut headers, known_headers);
            for param in &method.params {
                collect_type_headers(&Some(param.ty.clone()), &mut headers, known_headers);
            }
        }

        for method in &class.static_methods {
            collect_type_headers(&method.return_type, &mut headers, known_headers);
            for param in &method.params {
                collect_type_headers(&Some(param.ty.clone()), &mut headers, known_headers);
            }
        }

        for ctor in &class.constructors {
            for param in &ctor.params {
                collect_type_headers(&Some(param.ty.clone()), &mut headers, known_headers);
            }
        }
    }

    let mut result: Vec<_> = headers.into_iter().collect();
    result.sort();
    result
}

/// Collect all Handle types used in the classes
/// Returns (inner_class_name, handle_typedef_name) pairs
fn collect_handle_types(classes: &[&ParsedClass]) -> Vec<(String, String)> {
    let mut handles = HashSet::new();

    for class in classes {
        // Add Handle type for classes that are transient (can be wrapped in Handle)
        if class.is_handle_type && !class.has_protected_destructor {
            handles.insert(class.name.clone());
        }

        for method in &class.methods {
            collect_type_handles(&method.return_type, &mut handles);
            for param in &method.params {
                collect_type_handles(&Some(param.ty.clone()), &mut handles);
            }
        }

        for method in &class.static_methods {
            collect_type_handles(&method.return_type, &mut handles);
            for param in &method.params {
                collect_type_handles(&Some(param.ty.clone()), &mut handles);
            }
        }

        for ctor in &class.constructors {
            for param in &ctor.params {
                collect_type_handles(&Some(param.ty.clone()), &mut handles);
            }
        }
    }

    let mut result: Vec<_> = handles
        .into_iter()
        .map(|inner_class| {
            // Use full class name to match Rust side (e.g., HandleGeom2dCurve not HandleCurve)
            let handle_name = format!("Handle{}", inner_class.replace("_", ""));
            (inner_class, handle_name)
        })
        .collect();
    result.sort();
    result
}

/// Extract short class name without module prefix
fn extract_short_class_name(name: &str) -> String {
    if let Some(underscore_pos) = name.find('_') {
        name[underscore_pos + 1..].to_string()
    } else {
        name.to_string()
    }
}

/// Collect Handle type inner classes from a type
fn collect_type_handles(ty: &Option<Type>, handles: &mut HashSet<String>) {
    if let Some(ty) = ty {
        match ty {
            Type::Handle(name) => {
                handles.insert(name.clone());
            }
            Type::ConstRef(inner) | Type::MutRef(inner) | Type::ConstPtr(inner) | Type::MutPtr(inner) => {
                collect_type_handles(&Some(inner.as_ref().clone()), handles);
            }
            _ => {}
        }
    }
}

/// Collect headers needed for a type
/// Collect headers needed for a type
fn collect_type_headers(ty: &Option<Type>, headers: &mut HashSet<String>, known_headers: &HashSet<String>) {
    if let Some(ty) = ty {
        // Skip unbindable types (arrays, streams, void pointers, raw pointers, etc.)
        if ty.is_unbindable() {
            return;
        }

        match ty {
            Type::Class(name) => {
                // Skip primitive types that don't have headers
                // Also skip Standard_Address which is defined in Standard_TypeDef.hxx, not its own file
                if matches!(name.as_str(), 
                    "bool" | "char" | "int" | "unsigned" | "float" | "double" | 
                    "void" | "size_t" | "Standard_Address"
                ) {
                    return;
                }
                // Skip nested types (e.g., Message_Messenger::StreamBuffer resolved to just StreamBuffer)
                // OCCT classes follow Module_ClassName pattern, so classes without underscore
                // (except Standard types) are likely nested types that don't have their own header
                if !name.contains('_') && !name.starts_with("Standard") {
                    return;
                }
                // Only include headers that actually exist in the OCCT include directory
                let header = format!("{}.hxx", name);
                if known_headers.is_empty() || known_headers.contains(&header) {
                    headers.insert(header);
                }
            }
            Type::Handle(name) => {
                let header = format!("{}.hxx", name);
                if known_headers.is_empty() || known_headers.contains(&header) {
                    headers.insert(header);
                }
                headers.insert("Standard_Handle.hxx".to_string());
            }
            Type::ConstRef(inner) | Type::MutRef(inner) | Type::ConstPtr(inner) | Type::MutPtr(inner) => {
                collect_type_headers(&Some(inner.as_ref().clone()), headers, known_headers);
            }
            _ => {}
        }
    }
}

// Filter functions - delegate to centralized implementations in resolver module

/// Check if params and return type use any enum types
/// This is a convenience wrapper for the cpp codegen which passes params and return_type separately
fn method_uses_enum(params: &[Param], return_type: &Option<Type>, all_enums: &HashSet<String>) -> bool {
    resolver::params_use_enum(params, all_enums)
        || return_type.as_ref().map_or(false, |t| resolver::type_uses_enum(t, all_enums))
}

/// Generate C++ wrapper functions for a class
fn generate_class_wrappers(class: &ParsedClass, output: &mut String, symbol_table: &SymbolTable) {
    writeln!(output, "// ========================").unwrap();
    writeln!(output, "// {} wrappers", class.name).unwrap();
    writeln!(output, "// ========================").unwrap();
    writeln!(output).unwrap();

    // Generate constructor wrappers
    generate_constructor_wrappers(class, output, &symbol_table.all_enum_names);

    // Generate wrappers for methods that return by value
    generate_return_by_value_wrappers(class, output, &symbol_table.all_enum_names);

    // Generate wrappers for methods with const char* parameters
    generate_c_string_param_wrappers(class, output, &symbol_table.all_enum_names);

    // Generate wrappers for methods that return const char* (need rust::String conversion)
    generate_c_string_return_wrappers(class, output, &symbol_table.all_enum_names);

    // Generate static method wrappers
    generate_static_method_wrappers(class, output, &symbol_table.all_enum_names);

    // Generate upcast wrappers for inheritance
    generate_upcast_wrappers(class, output, symbol_table);

    // Generate to_handle wrapper for transient classes (classes that can be wrapped in Handle)
    generate_to_handle_wrapper(class, output);

    // Generate Handle upcast wrappers for Handle types where inner class has base classes
    generate_handle_upcast_wrappers(class, output, symbol_table);

    writeln!(output).unwrap();
}

/// Generate constructor wrapper functions
fn generate_constructor_wrappers(class: &ParsedClass, output: &mut String, all_enum_names: &HashSet<String>) {
    // Skip constructors for abstract classes (can't instantiate them)
    if class.is_abstract {
        return;
    }
    
    for (_i, ctor) in class.constructors.iter().enumerate() {
        // Skip constructors with class/handle parameters passed by value (not supported by CXX)
        if ctor.params.iter().any(|p| matches!(&p.ty, Type::Class(_) | Type::Handle(_))) {
            continue;
        }

        // Skip constructors with unbindable types (C strings, streams, void pointers, etc.)
        if ctor.has_unbindable_types() {
            continue;
        }
        
        // Skip constructors with enum types (enums not supported - CXX uses enum class but OCCT uses unscoped enums)
        if method_uses_enum(&ctor.params, &None, all_enum_names) {
            continue;
        }
        
        let suffix = if ctor.params.is_empty() {
            "ctor".to_string()
        } else {
            format!("ctor{}", ctor.overload_suffix())
        };

        // Handle duplicate suffixes
        let wrapper_name = format!("{}_{}", class.name, suffix);

        // Parameter list - use type_to_cpp_param for CXX-compatible types (e.g., rust::Str)
        let params = ctor
            .params
            .iter()
            .map(|p| format!("{} {}", type_to_cpp_param(&p.ty), p.name))
            .collect::<Vec<_>>()
            .join(", ");

        // Argument list for constructor call - convert from CXX types to native C++ types
        let args = ctor
            .params
            .iter()
            .map(|p| param_to_cpp_arg(p))
            .collect::<Vec<_>>()
            .join(", ");

        writeln!(
            output,
            "inline std::unique_ptr<{class_name}> {wrapper_name}({params}) {{",
            class_name = class.name,
        )
        .unwrap();
        writeln!(
            output,
            "    return std::make_unique<{class_name}>({args});",
            class_name = class.name,
        )
        .unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();
    }
}

/// Generate wrapper functions for methods that return by value
fn generate_return_by_value_wrappers(class: &ParsedClass, output: &mut String, all_enum_names: &HashSet<String>) {
    for method in &class.methods {
        if !method.returns_by_value() {
            continue;
        }

        // Skip methods with unbindable types (streams, void pointers, etc.)
        if method.has_unbindable_types() {
            continue;
        }
        
        // Skip methods with enum types (enums not supported - CXX uses enum class but OCCT uses unscoped enums)
        if method_uses_enum(&method.params, &method.return_type, all_enum_names) {
            continue;
        }

        let return_type = method.return_type.as_ref().unwrap();
        
        // Check if return type is an enum - enums don't need unique_ptr wrapping
        let return_type_name = match return_type {
            Type::Class(name) => Some(name.as_str()),
            _ => None,
        };
        let is_enum = return_type_name.map(|n| all_enum_names.contains(n)).unwrap_or(false);
        
        // Skip enum returns - they don't need wrapper functions
        if is_enum {
            continue;
        }
        
        let cpp_return_type = type_to_cpp(return_type);
        let wrapper_name = format!("{}_{}", class.name, method.name);

        // Self parameter
        let self_param = if method.is_const {
            format!("const {}& self", class.name)
        } else {
            format!("{}& self", class.name)
        };

        // Other parameters - use type_to_cpp_param for CXX-compatible types (e.g., rust::Str)
        let other_params = method
            .params
            .iter()
            .map(|p| format!("{} {}", type_to_cpp_param(&p.ty), p.name))
            .collect::<Vec<_>>()
            .join(", ");

        let params = if other_params.is_empty() {
            self_param
        } else {
            format!("{}, {}", self_param, other_params)
        };

        // Argument list for method call - convert from CXX types to native C++ types
        let args = method
            .params
            .iter()
            .map(|p| param_to_cpp_arg(p))
            .collect::<Vec<_>>()
            .join(", ");

        writeln!(
            output,
            "inline std::unique_ptr<{cpp_return_type}> {wrapper_name}({params}) {{"
        )
        .unwrap();
        writeln!(
            output,
            "    return std::make_unique<{cpp_return_type}>(self.{method_name}({args}));",
            method_name = method.name,
        )
        .unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();
    }
}

/// Generate wrapper functions for methods that have C string parameters
/// These methods need wrappers because CXX uses rust::Str which must be converted to const char*
fn generate_c_string_param_wrappers(class: &ParsedClass, output: &mut String, all_enum_names: &HashSet<String>) {
    for method in &class.methods {
        // Only wrap methods that have C string parameters
        let has_c_string_param = method.params.iter().any(|p| p.ty.is_c_string());
        if !has_c_string_param {
            continue;
        }
        
        // Skip methods with enum types (enums not supported - CXX uses enum class but OCCT uses unscoped enums)
        if method_uses_enum(&method.params, &method.return_type, all_enum_names) {
            continue;
        }
        
        // Check if method is already wrapped by generate_return_by_value_wrappers
        // That function wraps methods that return classes/handles by value, BUT it skips enums
        let return_type = method.return_type.as_ref();
        let is_already_wrapped = if method.returns_by_value() {
            // Check if return type is an enum - if so, it's NOT wrapped by return_by_value_wrappers
            let return_type_name = match return_type {
                Some(Type::Class(name)) => Some(name.as_str()),
                _ => None,
            };
            let is_enum = return_type_name.map(|n| all_enum_names.contains(n)).unwrap_or(false);
            // It's already wrapped ONLY if it returns by value AND is NOT an enum
            !is_enum
        } else {
            false
        };
        
        if is_already_wrapped {
            continue;
        }

        // Skip methods with unbindable types (streams, void pointers, etc.)
        if method.has_unbindable_types() {
            continue;
        }

        let wrapper_name = format!("{}_{}", class.name, method.name);

        // Self parameter
        let self_param = if method.is_const {
            format!("const {}& self", class.name)
        } else {
            format!("{}& self", class.name)
        };

        // Other parameters - use type_to_cpp_param for CXX-compatible types (e.g., rust::Str)
        let other_params = method
            .params
            .iter()
            .map(|p| format!("{} {}", type_to_cpp_param(&p.ty), p.name))
            .collect::<Vec<_>>()
            .join(", ");

        let params = if other_params.is_empty() {
            self_param
        } else {
            format!("{}, {}", self_param, other_params)
        };

        // Argument list for method call - convert from CXX types to native C++ types
        let args = method
            .params
            .iter()
            .map(|p| param_to_cpp_arg(p))
            .collect::<Vec<_>>()
            .join(", ");

        // Determine return type - check if const char* needs rust::String conversion
        let returns_c_string = method.return_type.as_ref().map(|t| t.is_c_string()).unwrap_or(false);
        let return_type_str = if returns_c_string {
            "rust::String".to_string()
        } else {
            match &method.return_type {
                Some(rt) => type_to_cpp(rt),
                None => "void".to_string(),
            }
        };
        
        // Check if return type is a reference - needs special handling
        let returns_reference = method.return_type.as_ref().map(|t| t.is_reference()).unwrap_or(false);
        
        if returns_c_string {
            // const char* -> rust::String conversion
            writeln!(
                output,
                "inline rust::String {wrapper_name}({params}) {{"
            )
            .unwrap();
            writeln!(
                output,
                "    return rust::String(self.{method_name}({args}));",
                method_name = method.name,
            )
            .unwrap();
        } else if returns_reference {
            // For reference returns, return the reference directly
            writeln!(
                output,
                "inline {return_type_str} {wrapper_name}({params}) {{"
            )
            .unwrap();
            writeln!(
                output,
                "    return self.{method_name}({args});",
                method_name = method.name,
            )
            .unwrap();
        } else if return_type_str == "void" {
            writeln!(
                output,
                "inline void {wrapper_name}({params}) {{"
            )
            .unwrap();
            writeln!(
                output,
                "    self.{method_name}({args});",
                method_name = method.name,
            )
            .unwrap();
        } else {
            writeln!(
                output,
                "inline {return_type_str} {wrapper_name}({params}) {{"
            )
            .unwrap();
            writeln!(
                output,
                "    return self.{method_name}({args});",
                method_name = method.name,
            )
            .unwrap();
        }
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();
    }
}

/// Generate wrapper functions for instance methods that return const char*
/// These need wrappers to convert const char* to rust::String
fn generate_c_string_return_wrappers(class: &ParsedClass, output: &mut String, all_enum_names: &HashSet<String>) {
    for method in &class.methods {
        // Only wrap methods that return const char*
        let returns_c_string = method.return_type.as_ref().map(|t| t.is_c_string()).unwrap_or(false);
        if !returns_c_string {
            continue;
        }
        
        // Skip methods with enum types (enums not supported - CXX uses enum class but OCCT uses unscoped enums)
        if method_uses_enum(&method.params, &method.return_type, all_enum_names) {
            continue;
        }
        
        // Skip if already wrapped by return_by_value_wrappers (won't happen for const char*)
        // or by c_string_param_wrappers (check for overlap)
        let has_c_string_param = method.params.iter().any(|p| p.ty.is_c_string());
        if has_c_string_param {
            // Already handled by generate_c_string_param_wrappers, but we need to update
            // that function to handle returns - actually, let's check: that function doesn't
            // convert the return to rust::String, so we need to skip those here and fix that function
            continue;
        }

        // Skip methods with unbindable types (streams, void pointers, etc.)
        if method.has_unbindable_types() {
            continue;
        }

        let wrapper_name = format!("{}_{}", class.name, method.name);

        // Self parameter
        let self_param = if method.is_const {
            format!("const {}& self", class.name)
        } else {
            format!("{}& self", class.name)
        };

        // Other parameters - use type_to_cpp_param for CXX-compatible types
        let other_params = method
            .params
            .iter()
            .map(|p| format!("{} {}", type_to_cpp_param(&p.ty), p.name))
            .collect::<Vec<_>>()
            .join(", ");

        let params = if other_params.is_empty() {
            self_param
        } else {
            format!("{}, {}", self_param, other_params)
        };

        // Argument list for method call - convert from CXX types to native C++ types
        let args = method
            .params
            .iter()
            .map(|p| param_to_cpp_arg(p))
            .collect::<Vec<_>>()
            .join(", ");

        // Return rust::String by converting from const char*
        writeln!(
            output,
            "inline rust::String {wrapper_name}({params}) {{"
        )
        .unwrap();
        writeln!(
            output,
            "    return rust::String(self.{method_name}({args}));",
            method_name = method.name,
        )
        .unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();
    }
}

/// Generate static method wrapper functions
fn generate_static_method_wrappers(class: &ParsedClass, output: &mut String, all_enum_names: &HashSet<String>) {
    for method in &class.static_methods {
        // Skip methods with stream parameters - CXX can't bind C++ streams
        if method.has_unbindable_types() {
            continue;
        }
        
        // Skip methods with enum types (enums not supported - CXX uses enum class but OCCT uses unscoped enums)
        if method_uses_enum(&method.params, &method.return_type, all_enum_names) {
            continue;
        }
        
        // Skip static methods that return bare references - these need lifetimes
        if method.return_type.as_ref().map(|t| t.is_reference()).unwrap_or(false) {
            continue;
        }
        
        // Skip static methods with class/handle parameters passed by value (not supported by CXX)
        // CXX doesn't allow passing opaque types by value
        if method.params.iter().any(|p| matches!(&p.ty, Type::Class(_) | Type::Handle(_))) {
            continue;
        }
        
        // Check if method returns const char* - needs wrapper returning rust::String
        let returns_c_string = method.return_type.as_ref().map(|t| t.is_c_string()).unwrap_or(false);

        // Count how many static methods have this name to determine if suffix is needed
        let static_same_name_count = class
            .static_methods
            .iter()
            .filter(|m| m.name == method.name)
            .count();
        
        // Also check for instance methods with the same name (they generate wrapper functions
        // with the same naming pattern: ClassName_method_name)
        let instance_same_name_exists = class
            .methods
            .iter()
            .any(|m| m.name == method.name);
        
        // Generate overload suffix based on parameter types
        // We need a suffix if:
        // 1. There are multiple static methods with this name, OR
        // 2. There's an instance method with the same name
        let overload_suffix = if static_same_name_count > 1 || instance_same_name_exists {
            method.overload_suffix()
        } else {
            String::new()
        };
        
        let wrapper_name = format!("{}_{}{}", class.name, method.name, overload_suffix);

        // Parameters - use type_to_cpp_param for CXX-compatible types (e.g., rust::Str)
        let params = method
            .params
            .iter()
            .map(|p| format!("{} {}", type_to_cpp_param(&p.ty), p.name))
            .collect::<Vec<_>>()
            .join(", ");

        // Arguments - convert from CXX types to native C++ types
        let args = method
            .params
            .iter()
            .map(|p| param_to_cpp_arg(p))
            .collect::<Vec<_>>()
            .join(", ");

        // Check if return type is an enum - enums don't need unique_ptr wrapping
        let return_type_name = method.return_type.as_ref().and_then(|t| {
            match t {
                Type::Class(name) => Some(name.as_str()),
                _ => None,
            }
        });
        let is_enum_return = return_type_name.map(|n| all_enum_names.contains(n)).unwrap_or(false);

        // Return type:
        // - const char* -> rust::String (CXX supports rust::String as return type)
        // - classes/handles -> std::unique_ptr<T>
        // - enums -> direct return
        let return_type = if returns_c_string {
            "rust::String".to_string()
        } else {
            method
                .return_type
                .as_ref()
                .map(|t| {
                    if (t.is_class() || t.is_handle()) && !is_enum_return {
                        format!("std::unique_ptr<{}>", type_to_cpp(t))
                    } else {
                        type_to_cpp(t)
                    }
                })
                .unwrap_or_else(|| "void".to_string())
        };

        let is_return_by_value = method
            .return_type
            .as_ref()
            .map(|t| (t.is_class() || t.is_handle()) && !is_enum_return)
            .unwrap_or(false);

        writeln!(output, "inline {return_type} {wrapper_name}({params}) {{").unwrap();

        if returns_c_string {
            // const char* -> rust::String conversion
            writeln!(
                output,
                "    return rust::String({class_name}::{method_name}({args}));",
                class_name = class.name,
                method_name = method.name,
            )
            .unwrap();
        } else if is_return_by_value {
            let inner_type = type_to_cpp(method.return_type.as_ref().unwrap());
            writeln!(
                output,
                "    return std::make_unique<{inner_type}>({class_name}::{method_name}({args}));",
                class_name = class.name,
                method_name = method.name,
            )
            .unwrap();
        } else if method.return_type.is_some() {
            writeln!(
                output,
                "    return {class_name}::{method_name}({args});",
                class_name = class.name,
                method_name = method.name,
            )
            .unwrap();
        } else {
            writeln!(
                output,
                "    {class_name}::{method_name}({args});",
                class_name = class.name,
                method_name = method.name,
            )
            .unwrap();
        }

        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();
    }
}

/// Convert our Type to C++ type string for wrapper function parameters
/// This handles the CXX bridge interface (e.g., rust::Str for string inputs)
fn type_to_cpp_param(ty: &Type) -> String {
    match ty {
        // const char* parameters should accept rust::Str from CXX
        Type::ConstPtr(inner) if matches!(inner.as_ref(), Type::Class(name) if name == "char") => {
            "rust::Str".to_string()
        }
        _ => type_to_cpp(ty),
    }
}

/// Convert parameter to the argument form needed when calling OCCT functions
/// This converts from CXX types to native C++ types (e.g., rust::Str -> const char*)
fn param_to_cpp_arg(param: &Param) -> String {
    match &param.ty {
        // Convert rust::Str to const char* via std::string
        Type::ConstPtr(inner) if matches!(inner.as_ref(), Type::Class(name) if name == "char") => {
            format!("std::string({}).c_str()", param.name)
        }
        _ => param.name.clone(),
    }
}

/// Convert our Type to C++ type string
fn type_to_cpp(ty: &Type) -> String {
    match ty {
        Type::Void => "void".to_string(),
        Type::Bool => "Standard_Boolean".to_string(),
        Type::I32 => "Standard_Integer".to_string(),
        Type::U32 => "unsigned int".to_string(),
        Type::I64 => "long".to_string(),
        Type::U64 => "unsigned long long".to_string(),
        Type::Usize => "size_t".to_string(),
        Type::F32 => "float".to_string(),
        Type::F64 => "Standard_Real".to_string(),
        Type::ConstRef(inner) => format!("const {}&", type_to_cpp(inner)),
        Type::MutRef(inner) => format!("{}&", type_to_cpp(inner)),
        Type::RValueRef(inner) => format!("{}&&", type_to_cpp(inner)),
        Type::ConstPtr(inner) => format!("const {}*", type_to_cpp(inner)),
        Type::MutPtr(inner) => format!("{}*", type_to_cpp(inner)),
        Type::Handle(name) => format!("opencascade::handle<{}>", name),
        Type::Class(name) => name.clone(),
    }
}

/// Build a transitive inheritance map from all classes
/// Returns a map of class_name -> all_ancestor_names
pub fn build_inheritance_map(classes: &[&ParsedClass]) -> std::collections::HashMap<String, Vec<String>> {
    use std::collections::{HashMap, HashSet};
    
    let mut inheritance_map: HashMap<String, Vec<String>> = HashMap::new();
    
    // First, collect direct inheritance relationships
    for class in classes {
        let mut bases = class.base_classes.clone();
        bases.sort(); // Sort for deterministic ordering
        inheritance_map.insert(class.name.clone(), bases);
    }
    
    // Build transitive closure using repeated expansion
    // Keep expanding until no new relationships are found
    let mut changed = true;
    while changed {
        changed = false;
        let current_map = inheritance_map.clone();
        
        for (_class_name, ancestors) in inheritance_map.iter_mut() {
            let mut new_ancestors = HashSet::new();
            
            // Add existing ancestors
            for ancestor in ancestors.iter() {
                new_ancestors.insert(ancestor.clone());
                
                // Add ancestors of ancestors
                if let Some(ancestor_ancestors) = current_map.get(ancestor) {
                    for ancestor_ancestor in ancestor_ancestors {
                        new_ancestors.insert(ancestor_ancestor.clone());
                    }
                }
            }
            
            let mut new_vec: Vec<String> = new_ancestors.into_iter().collect();
            new_vec.sort(); // Sort for deterministic ordering
            if new_vec.len() != ancestors.len() {
                *ancestors = new_vec;
                changed = true;
            }
        }
    }
    
    inheritance_map
}

/// Generate upcast wrapper functions for inheritance
/// For each ancestor class, generates functions that cast from derived to ancestor (const and mutable)
fn generate_upcast_wrappers(class: &ParsedClass, output: &mut String, symbol_table: &SymbolTable) {
    // Get all ancestors for this class
    let ancestors = symbol_table.get_all_ancestors_by_name(&class.name);
    
    for base_class in &ancestors {
        // Skip base classes that aren't in our known set of classes
        // This filters out types from modules we haven't parsed (e.g., XSControl)
        if !symbol_table.all_class_names.contains(base_class) {
            continue;
        }
        
        // Generate const upcast:
        // inline const BaseClass& DerivedClass_as_BaseClass(const DerivedClass& self) { return self; }
        let wrapper_name = format!("{}_as_{}", class.name, base_class.replace("::", "_"));
        writeln!(
            output,
            "inline const {}& {}(const {}& self) {{ return self; }}",
            base_class, wrapper_name, class.name
        )
        .unwrap();
        
        // Generate mutable upcast:
        // inline BaseClass& DerivedClass_as_BaseClass_mut(DerivedClass& self) { return self; }
        let wrapper_name_mut = format!("{}_as_{}_mut", class.name, base_class.replace("::", "_"));
        writeln!(
            output,
            "inline {}& {}({}& self) {{ return self; }}",
            base_class, wrapper_name_mut, class.name
        )
        .unwrap();
    }
}

/// Generate to_handle wrapper for transient classes
/// Generates a function that wraps an object in a Handle (reference-counted smart pointer)
fn generate_to_handle_wrapper(class: &ParsedClass, output: &mut String) {
    // Only generate for classes that are Handle types (inherit from Standard_Transient)
    if !class.is_handle_type {
        return;
    }

    // Skip classes with protected destructors - they can't be owned by UniquePtr
    if class.has_protected_destructor {
        return;
    }

    // Skip abstract classes - they can't be instantiated or owned by UniquePtr
    if class.is_abstract {
        return;
    }

    // Handle type name: Handle{ClassName} with underscores removed
    let handle_type_name = format!("Handle{}", class.name.replace("_", ""));
    
    // Generate: 
    // inline std::unique_ptr<Handle(ClassName)> ClassName_to_handle(std::unique_ptr<ClassName> obj) {
    //     return std::make_unique<Handle(ClassName)>(obj.release());
    // }
    let wrapper_name = format!("{}_to_handle", class.name);
    writeln!(
        output,
        "inline std::unique_ptr<{}> {}(std::unique_ptr<{}> obj) {{",
        handle_type_name, wrapper_name, class.name
    )
    .unwrap();
    writeln!(
        output,
        "    return std::make_unique<{}>(obj.release());",
        handle_type_name
    )
    .unwrap();
    writeln!(output, "}}").unwrap();
}

/// Generate Handle upcast wrapper functions for inheritance
/// For each ancestor Handle type, generates functions to upcast to Handle of ancestor class
fn generate_handle_upcast_wrappers(class: &ParsedClass, output: &mut String, symbol_table: &SymbolTable) {
    // Only generate for Handle types (classes that inherit from Standard_Transient)
    if !class.is_handle_type {
        return;
    }

    // Skip classes with protected destructors
    if class.has_protected_destructor {
        return;
    }

    // NOTE: We DO generate handle upcasts for abstract classes.
    // Handle upcasting doesn't instantiate the class - it just copies the Handle
    // pointer to a base Handle type, which is always valid.

    // Handle type name for this class
    let handle_type_name = format!("Handle{}", class.name.replace("_", ""));

    // Get all ancestors for this class
    let ancestors = symbol_table.get_all_ancestors_by_name(&class.name);
    
    for base_class in &ancestors {
        // Skip base classes that aren't in our known set of classes
        if !symbol_table.all_class_names.contains(base_class) {
            continue;
        }

        // Base handle type name
        let base_handle_type_name = format!("Handle{}", base_class.replace("_", ""));

        // Generate:
        // inline std::unique_ptr<HandleBaseClass> HandleDerivedClass_to_HandleBaseClass(
        //     const HandleDerivedClass& handle) {
        //     return std::make_unique<HandleBaseClass>(handle);
        // }
        let wrapper_name = format!("{}_to_{}", handle_type_name, base_handle_type_name);
        writeln!(
            output,
            "inline std::unique_ptr<{}> {}(const {}& handle) {{",
            base_handle_type_name, wrapper_name, handle_type_name
        )
        .unwrap();
        writeln!(
            output,
            "    return std::make_unique<{}>(handle);",
            base_handle_type_name
        )
        .unwrap();
        writeln!(output, "}}").unwrap();
    }
}

/// Generate C++ wrappers for namespace-level free functions
/// These wrapper functions call the original namespace functions and are exposed via CXX
fn generate_function_wrappers(
    module_name: &str,
    functions: &[&ParsedFunction],
    output: &mut String,
    symbol_table: &SymbolTable,
    known_headers: &HashSet<String>,
) {
    // Skip if no functions
    if functions.is_empty() {
        return;
    }
    
    // Collect additional headers needed for functions
    let mut extra_headers: HashSet<String> = HashSet::new();
    for func in functions {
        // The function is defined in the namespace header (e.g., TopoDS.hxx for TopoDS::Edge)
        extra_headers.insert(format!("{}.hxx", module_name));
        
        // Also collect headers for parameter and return types
        for param in &func.params {
            collect_type_headers(&Some(param.ty.clone()), &mut extra_headers, known_headers);
        }
        if let Some(ref ret_ty) = func.return_type {
            collect_type_headers(&Some(ret_ty.clone()), &mut extra_headers, known_headers);
        }
    }
    
    // Output additional includes
    for header in extra_headers {
        writeln!(output, "#include <{}>", header).unwrap();
    }
    writeln!(output).unwrap();
    
    writeln!(output, "// Namespace function wrappers for {}", module_name).unwrap();
    
    // Track function names to detect overloads (must match Rust codegen logic)
    let mut seen_names: std::collections::HashMap<String, usize> = std::collections::HashMap::new();
    
    for func in functions {
        // Skip functions with unbindable types
        if func.has_unbindable_types() {
            continue;
        }
        
        // Skip functions with enum types (enums not supported - CXX uses enum class but OCCT uses unscoped enums)
        if method_uses_enum(&func.params, &func.return_type, &symbol_table.all_enum_names) {
            continue;
        }
        
        // Generate wrapper function
        // The wrapper is named Module_fn_FunctionName to avoid clashing with type names
        // (e.g., TopoDS_fn_Vertex instead of TopoDS_Vertex which clashes with the class)
        let base_wrapper_name = format!("{}_fn_{}", module_name, func.short_name);
        
        // Check if this is a const or mut version (for overloads)
        let is_mut_version = func.params.iter().any(|p| matches!(&p.ty, Type::MutRef(_)));
        
        // Track overloads and give unique names (must match Rust codegen logic)
        let base_rust_name = heck::AsSnakeCase(&func.short_name).to_string();
        let count = seen_names.entry(base_rust_name.clone()).or_insert(0);
        *count += 1;
        
        // If this is an overload (count > 1), add a suffix
        let wrapper_name = if *count > 1 {
            let suffix = if is_mut_version { "_mut" } else { &format!("_{}", count) };
            format!("{}{}", base_wrapper_name, suffix)
        } else {
            base_wrapper_name
        };
        
        // Determine return type
        let return_type_cpp = match &func.return_type {
            Some(ty) => type_to_cpp(ty),
            None => "void".to_string(),
        };
        
        // Generate parameter list for the wrapper function
        let params_cpp: Vec<String> = func.params.iter()
            .map(|p| format!("{} {}", type_to_cpp_param(&p.ty), p.name))
            .collect();
        let params_str = params_cpp.join(", ");
        
        // Generate argument list for calling the original function
        let args_str: Vec<String> = func.params.iter()
            .map(|p| param_to_cpp_arg(p))
            .collect();
        let args = args_str.join(", ");
        
        // Call the namespace function
        let call = format!("{}::{}({})", module_name, func.short_name, args);
        
        writeln!(
            output,
            "inline {} {}({}) {{ return {}; }}",
            return_type_cpp, wrapper_name, params_str, call
        ).unwrap();
    }
    writeln!(output).unwrap();
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::Param;

    #[test]
    fn test_type_to_cpp() {
        assert_eq!(type_to_cpp(&Type::F64), "Standard_Real");
        assert_eq!(type_to_cpp(&Type::I32), "Standard_Integer");
        assert_eq!(type_to_cpp(&Type::Class("gp_Pnt".to_string())), "gp_Pnt");
        assert_eq!(
            type_to_cpp(&Type::ConstRef(Box::new(Type::Class("gp_Pnt".to_string())))),
            "const gp_Pnt&"
        );
    }
}
