//! C++ wrapper code generation
//!
//! Generates C++ wrapper functions for patterns that CXX can't handle directly:
//! - Constructors (using construct_unique template)
//! - Return-by-value methods
//! - Static methods
//! - Overloaded methods

use crate::model::{Param, ParsedClass, Type};
use crate::module_graph::{CrossModuleType, Module};
use std::collections::HashSet;
use std::fmt::Write;

/// Generate the common.hxx header with shared utilities
pub fn generate_common_header() -> String {
    r#"// Generated by opencascade-binding-generator
// Common utilities for CXX bridge

#pragma once
#include "rust/cxx.h"
#include <memory>

// Generic template constructor - creates a UniquePtr to a newly constructed T
template <typename T, typename... Args>
std::unique_ptr<T> construct_unique(Args... args) {
    return std::unique_ptr<T>(new T(args...));
}
"#
    .to_string()
}

/// Generate the C++ header for a module
pub fn generate_module_header(
    module: &Module,
    classes: &[&ParsedClass],
    _cross_module_types: &[CrossModuleType],
    all_enum_names: &HashSet<String>,
) -> String {
    let mut output = String::new();

    // Header guard and includes
    writeln!(output, "// Generated by opencascade-binding-generator").unwrap();
    writeln!(output, "// C++ wrappers for {} module", module.name).unwrap();
    writeln!(output).unwrap();
    writeln!(output, "#pragma once").unwrap();
    writeln!(output, "#include \"common.hxx\"").unwrap();
    writeln!(output).unwrap();

    // Collect all OCCT headers needed
    let headers = collect_required_headers(classes);
    for header in headers {
        writeln!(output, "#include <{}>", header).unwrap();
    }
    writeln!(output).unwrap();

    // Generate Handle typedefs
    let handle_types = collect_handle_types(classes);
    if !handle_types.is_empty() {
        writeln!(output, "// Handle type aliases").unwrap();
        for (inner_class, handle_name) in &handle_types {
            writeln!(
                output,
                "typedef opencascade::handle<{}> {};",
                inner_class, handle_name
            )
            .unwrap();
        }
        writeln!(output).unwrap();
    }

    // Generate wrapper functions for each class
    for class in classes {
        generate_class_wrappers(class, &mut output, all_enum_names);
    }

    output
}

/// Collect all OCCT headers needed for a set of classes
fn collect_required_headers(classes: &[&ParsedClass]) -> Vec<String> {
    let mut headers = HashSet::new();

    for class in classes {
        // Add header for the class itself
        headers.insert(format!("{}.hxx", class.name));

        // Add headers for types used in methods
        for method in &class.methods {
            collect_type_headers(&method.return_type, &mut headers);
            for param in &method.params {
                collect_type_headers(&Some(param.ty.clone()), &mut headers);
            }
        }

        for method in &class.static_methods {
            collect_type_headers(&method.return_type, &mut headers);
            for param in &method.params {
                collect_type_headers(&Some(param.ty.clone()), &mut headers);
            }
        }

        for ctor in &class.constructors {
            for param in &ctor.params {
                collect_type_headers(&Some(param.ty.clone()), &mut headers);
            }
        }
    }

    let mut result: Vec<_> = headers.into_iter().collect();
    result.sort();
    result
}

/// Collect all Handle types used in the classes
/// Returns (inner_class_name, handle_typedef_name) pairs
fn collect_handle_types(classes: &[&ParsedClass]) -> Vec<(String, String)> {
    let mut handles = HashSet::new();

    for class in classes {
        for method in &class.methods {
            collect_type_handles(&method.return_type, &mut handles);
            for param in &method.params {
                collect_type_handles(&Some(param.ty.clone()), &mut handles);
            }
        }

        for method in &class.static_methods {
            collect_type_handles(&method.return_type, &mut handles);
            for param in &method.params {
                collect_type_handles(&Some(param.ty.clone()), &mut handles);
            }
        }

        for ctor in &class.constructors {
            for param in &ctor.params {
                collect_type_handles(&Some(param.ty.clone()), &mut handles);
            }
        }
    }

    let mut result: Vec<_> = handles
        .into_iter()
        .map(|inner_class| {
            // Use full class name to match Rust side (e.g., HandleGeom2dCurve not HandleCurve)
            let handle_name = format!("Handle{}", inner_class.replace("_", ""));
            (inner_class, handle_name)
        })
        .collect();
    result.sort();
    result
}

/// Extract short class name without module prefix
fn extract_short_class_name(name: &str) -> String {
    if let Some(underscore_pos) = name.find('_') {
        name[underscore_pos + 1..].to_string()
    } else {
        name.to_string()
    }
}

/// Collect Handle type inner classes from a type
fn collect_type_handles(ty: &Option<Type>, handles: &mut HashSet<String>) {
    if let Some(ty) = ty {
        match ty {
            Type::Handle(name) => {
                handles.insert(name.clone());
            }
            Type::ConstRef(inner) | Type::MutRef(inner) | Type::ConstPtr(inner) | Type::MutPtr(inner) => {
                collect_type_handles(&Some(inner.as_ref().clone()), handles);
            }
            _ => {}
        }
    }
}

/// Collect headers needed for a type
fn collect_type_headers(ty: &Option<Type>, headers: &mut HashSet<String>) {
    if let Some(ty) = ty {
        // Skip unbindable types (arrays, streams, void pointers, raw pointers, etc.)
        if ty.is_unbindable() {
            return;
        }

        match ty {
            Type::Class(name) => {
                // Skip primitive types that don't have headers
                // Also skip Standard_Address which is defined in Standard_TypeDef.hxx, not its own file
                if !matches!(name.as_str(), 
                    "bool" | "char" | "int" | "unsigned" | "float" | "double" | 
                    "void" | "size_t" | "Standard_Address"
                ) {
                    headers.insert(format!("{}.hxx", name));
                }
            }
            Type::Handle(name) => {
                headers.insert(format!("{}.hxx", name));
                headers.insert("Standard_Handle.hxx".to_string());
            }
            Type::ConstRef(inner) | Type::MutRef(inner) | Type::ConstPtr(inner) | Type::MutPtr(inner) => {
                collect_type_headers(&Some(inner.as_ref().clone()), headers);
            }
            _ => {}
        }
    }
}

/// Generate C++ wrapper functions for a class
fn generate_class_wrappers(class: &ParsedClass, output: &mut String, all_enum_names: &HashSet<String>) {
    writeln!(output, "// ========================").unwrap();
    writeln!(output, "// {} wrappers", class.name).unwrap();
    writeln!(output, "// ========================").unwrap();
    writeln!(output).unwrap();

    // Generate constructor wrappers
    generate_constructor_wrappers(class, output);

    // Generate wrappers for methods that return by value
    generate_return_by_value_wrappers(class, output, all_enum_names);

    // Generate wrappers for methods with const char* parameters
    generate_c_string_param_wrappers(class, output, all_enum_names);

    // Generate static method wrappers
    generate_static_method_wrappers(class, output, all_enum_names);

    writeln!(output).unwrap();
}

/// Generate constructor wrapper functions
fn generate_constructor_wrappers(class: &ParsedClass, output: &mut String) {
    for (_i, ctor) in class.constructors.iter().enumerate() {
        // Skip constructors with class/handle parameters passed by value (not supported by CXX)
        if ctor.params.iter().any(|p| matches!(&p.ty, Type::Class(_) | Type::Handle(_))) {
            continue;
        }

        // Skip constructors with unbindable types (C strings, streams, void pointers, etc.)
        if ctor.has_unbindable_types() {
            continue;
        }
        
        let suffix = if ctor.params.is_empty() {
            "ctor".to_string()
        } else {
            format!("ctor{}", ctor.overload_suffix())
        };

        // Handle duplicate suffixes
        let wrapper_name = format!("{}_{}", class.name, suffix);

        // Parameter list - use type_to_cpp_param for CXX-compatible types (e.g., rust::Str)
        let params = ctor
            .params
            .iter()
            .map(|p| format!("{} {}", type_to_cpp_param(&p.ty), p.name))
            .collect::<Vec<_>>()
            .join(", ");

        // Argument list for constructor call - convert from CXX types to native C++ types
        let args = ctor
            .params
            .iter()
            .map(|p| param_to_cpp_arg(p))
            .collect::<Vec<_>>()
            .join(", ");

        writeln!(
            output,
            "inline std::unique_ptr<{class_name}> {wrapper_name}({params}) {{",
            class_name = class.name,
        )
        .unwrap();
        writeln!(
            output,
            "    return construct_unique<{class_name}>({args});",
            class_name = class.name,
        )
        .unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();
    }
}

/// Generate wrapper functions for methods that return by value
fn generate_return_by_value_wrappers(class: &ParsedClass, output: &mut String, all_enum_names: &HashSet<String>) {
    for method in &class.methods {
        if !method.returns_by_value() {
            continue;
        }

        // Skip methods with unbindable types (streams, void pointers, etc.)
        if method.has_unbindable_types() {
            continue;
        }

        let return_type = method.return_type.as_ref().unwrap();
        
        // Check if return type is an enum - enums don't need unique_ptr wrapping
        let return_type_name = match return_type {
            Type::Class(name) => Some(name.as_str()),
            _ => None,
        };
        let is_enum = return_type_name.map(|n| all_enum_names.contains(n)).unwrap_or(false);
        
        // Skip enum returns - they don't need wrapper functions
        if is_enum {
            continue;
        }
        
        let cpp_return_type = type_to_cpp(return_type);
        let wrapper_name = format!("{}_{}", class.name, method.name);

        // Self parameter
        let self_param = if method.is_const {
            format!("const {}& self", class.name)
        } else {
            format!("{}& self", class.name)
        };

        // Other parameters - use type_to_cpp_param for CXX-compatible types (e.g., rust::Str)
        let other_params = method
            .params
            .iter()
            .map(|p| format!("{} {}", type_to_cpp_param(&p.ty), p.name))
            .collect::<Vec<_>>()
            .join(", ");

        let params = if other_params.is_empty() {
            self_param
        } else {
            format!("{}, {}", self_param, other_params)
        };

        // Argument list for method call - convert from CXX types to native C++ types
        let args = method
            .params
            .iter()
            .map(|p| param_to_cpp_arg(p))
            .collect::<Vec<_>>()
            .join(", ");

        writeln!(
            output,
            "inline std::unique_ptr<{cpp_return_type}> {wrapper_name}({params}) {{"
        )
        .unwrap();
        writeln!(
            output,
            "    return std::make_unique<{cpp_return_type}>(self.{method_name}({args}));",
            method_name = method.name,
        )
        .unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();
    }
}

/// Generate wrapper functions for methods that have C string parameters
/// These methods need wrappers because CXX uses rust::Str which must be converted to const char*
fn generate_c_string_param_wrappers(class: &ParsedClass, output: &mut String, all_enum_names: &HashSet<String>) {
    for method in &class.methods {
        // Only wrap methods that have C string parameters
        let has_c_string_param = method.params.iter().any(|p| p.ty.is_c_string());
        if !has_c_string_param {
            continue;
        }
        
        // Check if method is already wrapped by generate_return_by_value_wrappers
        // That function wraps methods that return classes/handles by value, BUT it skips enums
        let return_type = method.return_type.as_ref();
        let is_already_wrapped = if method.returns_by_value() {
            // Check if return type is an enum - if so, it's NOT wrapped by return_by_value_wrappers
            let return_type_name = match return_type {
                Some(Type::Class(name)) => Some(name.as_str()),
                _ => None,
            };
            let is_enum = return_type_name.map(|n| all_enum_names.contains(n)).unwrap_or(false);
            // It's already wrapped ONLY if it returns by value AND is NOT an enum
            !is_enum
        } else {
            false
        };
        
        if is_already_wrapped {
            continue;
        }

        // Skip methods with unbindable types (streams, void pointers, etc.)
        if method.has_unbindable_types() {
            continue;
        }

        let wrapper_name = format!("{}_{}", class.name, method.name);

        // Self parameter
        let self_param = if method.is_const {
            format!("const {}& self", class.name)
        } else {
            format!("{}& self", class.name)
        };

        // Other parameters - use type_to_cpp_param for CXX-compatible types (e.g., rust::Str)
        let other_params = method
            .params
            .iter()
            .map(|p| format!("{} {}", type_to_cpp_param(&p.ty), p.name))
            .collect::<Vec<_>>()
            .join(", ");

        let params = if other_params.is_empty() {
            self_param
        } else {
            format!("{}, {}", self_param, other_params)
        };

        // Argument list for method call - convert from CXX types to native C++ types
        let args = method
            .params
            .iter()
            .map(|p| param_to_cpp_arg(p))
            .collect::<Vec<_>>()
            .join(", ");

        // Determine return type
        let return_type_str = match &method.return_type {
            Some(rt) => type_to_cpp(rt),
            None => "void".to_string(),
        };
        
        // Check if return type is a reference - needs special handling
        let returns_reference = method.return_type.as_ref().map(|t| t.is_reference()).unwrap_or(false);
        
        if returns_reference {
            // For reference returns, return the reference directly
            writeln!(
                output,
                "inline {return_type_str} {wrapper_name}({params}) {{"
            )
            .unwrap();
            writeln!(
                output,
                "    return self.{method_name}({args});",
                method_name = method.name,
            )
            .unwrap();
        } else if return_type_str == "void" {
            writeln!(
                output,
                "inline void {wrapper_name}({params}) {{"
            )
            .unwrap();
            writeln!(
                output,
                "    self.{method_name}({args});",
                method_name = method.name,
            )
            .unwrap();
        } else {
            writeln!(
                output,
                "inline {return_type_str} {wrapper_name}({params}) {{"
            )
            .unwrap();
            writeln!(
                output,
                "    return self.{method_name}({args});",
                method_name = method.name,
            )
            .unwrap();
        }
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();
    }
}

/// Generate static method wrapper functions
fn generate_static_method_wrappers(class: &ParsedClass, output: &mut String, all_enum_names: &HashSet<String>) {
    for method in &class.static_methods {
        // Skip methods with stream parameters - CXX can't bind C++ streams
        if method.has_unbindable_types() {
            continue;
        }
        
        // Skip static methods that return bare references - these need lifetimes
        if method.return_type.as_ref().map(|t| t.is_reference()).unwrap_or(false) {
            continue;
        }
        
        // Check if method returns const char* - needs wrapper returning rust::String
        let returns_c_string = method.return_type.as_ref().map(|t| t.is_c_string()).unwrap_or(false);

        // Count how many static methods have this name to determine if suffix is needed
        let same_name_count = class
            .static_methods
            .iter()
            .filter(|m| m.name == method.name)
            .count();
        
        // Generate overload suffix based on parameter types
        let overload_suffix = if same_name_count > 1 {
            method.overload_suffix()
        } else {
            String::new()
        };
        
        let wrapper_name = format!("{}_{}{}", class.name, method.name, overload_suffix);

        // Parameters - use type_to_cpp_param for CXX-compatible types (e.g., rust::Str)
        let params = method
            .params
            .iter()
            .map(|p| format!("{} {}", type_to_cpp_param(&p.ty), p.name))
            .collect::<Vec<_>>()
            .join(", ");

        // Arguments - convert from CXX types to native C++ types
        let args = method
            .params
            .iter()
            .map(|p| param_to_cpp_arg(p))
            .collect::<Vec<_>>()
            .join(", ");

        // Check if return type is an enum - enums don't need unique_ptr wrapping
        let return_type_name = method.return_type.as_ref().and_then(|t| {
            match t {
                Type::Class(name) => Some(name.as_str()),
                _ => None,
            }
        });
        let is_enum_return = return_type_name.map(|n| all_enum_names.contains(n)).unwrap_or(false);

        // Return type:
        // - const char* -> rust::String (CXX supports rust::String as return type)
        // - classes/handles -> std::unique_ptr<T>
        // - enums -> direct return
        let return_type = if returns_c_string {
            "rust::String".to_string()
        } else {
            method
                .return_type
                .as_ref()
                .map(|t| {
                    if (t.is_class() || t.is_handle()) && !is_enum_return {
                        format!("std::unique_ptr<{}>", type_to_cpp(t))
                    } else {
                        type_to_cpp(t)
                    }
                })
                .unwrap_or_else(|| "void".to_string())
        };

        let is_return_by_value = method
            .return_type
            .as_ref()
            .map(|t| (t.is_class() || t.is_handle()) && !is_enum_return)
            .unwrap_or(false);

        writeln!(output, "inline {return_type} {wrapper_name}({params}) {{").unwrap();

        if returns_c_string {
            // const char* -> rust::String conversion
            writeln!(
                output,
                "    return rust::String({class_name}::{method_name}({args}));",
                class_name = class.name,
                method_name = method.name,
            )
            .unwrap();
        } else if is_return_by_value {
            let inner_type = type_to_cpp(method.return_type.as_ref().unwrap());
            writeln!(
                output,
                "    return std::make_unique<{inner_type}>({class_name}::{method_name}({args}));",
                class_name = class.name,
                method_name = method.name,
            )
            .unwrap();
        } else if method.return_type.is_some() {
            writeln!(
                output,
                "    return {class_name}::{method_name}({args});",
                class_name = class.name,
                method_name = method.name,
            )
            .unwrap();
        } else {
            writeln!(
                output,
                "    {class_name}::{method_name}({args});",
                class_name = class.name,
                method_name = method.name,
            )
            .unwrap();
        }

        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();
    }
}

/// Convert our Type to C++ type string for wrapper function parameters
/// This handles the CXX bridge interface (e.g., rust::Str for string inputs)
fn type_to_cpp_param(ty: &Type) -> String {
    match ty {
        // const char* parameters should accept rust::Str from CXX
        Type::ConstPtr(inner) if matches!(inner.as_ref(), Type::Class(name) if name == "char") => {
            "rust::Str".to_string()
        }
        _ => type_to_cpp(ty),
    }
}

/// Convert parameter to the argument form needed when calling OCCT functions
/// This converts from CXX types to native C++ types (e.g., rust::Str -> const char*)
fn param_to_cpp_arg(param: &Param) -> String {
    match &param.ty {
        // Convert rust::Str to const char* via std::string
        Type::ConstPtr(inner) if matches!(inner.as_ref(), Type::Class(name) if name == "char") => {
            format!("std::string({}).c_str()", param.name)
        }
        _ => param.name.clone(),
    }
}

/// Convert our Type to C++ type string
fn type_to_cpp(ty: &Type) -> String {
    match ty {
        Type::Void => "void".to_string(),
        Type::Bool => "Standard_Boolean".to_string(),
        Type::I32 => "Standard_Integer".to_string(),
        Type::U32 => "unsigned int".to_string(),
        Type::I64 => "long".to_string(),
        Type::U64 => "unsigned long long".to_string(),
        Type::Usize => "size_t".to_string(),
        Type::F32 => "float".to_string(),
        Type::F64 => "Standard_Real".to_string(),
        Type::ConstRef(inner) => format!("const {}&", type_to_cpp(inner)),
        Type::MutRef(inner) => format!("{}&", type_to_cpp(inner)),
        Type::ConstPtr(inner) => format!("const {}*", type_to_cpp(inner)),
        Type::MutPtr(inner) => format!("{}*", type_to_cpp(inner)),
        Type::Handle(name) => format!("opencascade::handle<{}>", name),
        Type::Class(name) => name.clone(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::Param;

    #[test]
    fn test_generate_common_header() {
        let header = generate_common_header();
        assert!(header.contains("construct_unique"));
        assert!(header.contains("std::unique_ptr"));
    }

    #[test]
    fn test_type_to_cpp() {
        assert_eq!(type_to_cpp(&Type::F64), "Standard_Real");
        assert_eq!(type_to_cpp(&Type::I32), "Standard_Integer");
        assert_eq!(type_to_cpp(&Type::Class("gp_Pnt".to_string())), "gp_Pnt");
        assert_eq!(
            type_to_cpp(&Type::ConstRef(Box::new(Type::Class("gp_Pnt".to_string())))),
            "const gp_Pnt&"
        );
    }
}
